# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetDonate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetDonate
  pod 'ReachabilitySwift'
  pod 'SDWebImage'
  target 'GetDonateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetDonateUITests' do
    # Pods for testing
  end

end
